version: '3.8'

services:
  # TON FRONTEND
  frontend:
    image: ghcr.io/arthurbosshardt/cv-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    # On garde le lien avec le backend

  # TON BACKEND
  backend-service:
    image: ghcr.io/arthurbosshardt/cv-backend:latest
    ports:
      - "8080:5000"
    restart: always

watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    # Force Docker à utiliser l'architecture du système hôte
    platform: linux/arm64 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro
    command: --interval 300 --cleanup
    restart: always